apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0ofy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-0ofy@sha256:3beb4a441a994979e9c2d68068e5e3b4f80577dabf6bfaf72d059a0ddb7e02e0
        name: my-nodejs
        resources: {}
status: {}
